### ISSUE TITLE
Claude2 反代好不稳定，经常500，尤其今天晚上。。

### ISSUE THREAD

**Issue by darrelwangsz** [UNICKCHENG/openai-proxy#29]

**Comment by UNICKCHENG** [comment]
@darrelwangsz 再试一试？

**Comment by darrelwangsz** [comment]
Traceback (most recent call last):
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/requests/models.py", line 960, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "<input>", line 95, in send_message
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/requests/models.py", line 968, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

还是有问题，我试了几次只有一次成功，都是回复500。
我观察了下几个现象：
1、Claude2看，一大堆回复成功的。 
2、确实500失败。 

我是通过正文的send_message接口，是不是因为输入太长，因为我也不知道如何用附件的方式来给到。。。

**Comment by UNICKCHENG** [comment]
@darrelwangsz  你是自建的还是使用 `https://openai.aihey.cc` ？看日志似乎是因为网络请求中断，导致在接收数据流时 JSON 解析失败

**Comment by UNICKCHENG** [comment]
试一试这个能不能正常接收？

```python
import openai
openai.api_base = 'https://openai.aihey.cc/claude/{}/v1'.format(ORG_ID)
openai.api_key = SESSION_KEY

completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", 
                                          messages=[{"role": "user", "content": "讲一个笑话呗"}])
print(completion.choices[0].message.content)
```

```python
import openai
openai.api_base = 'https://openai.aihey.cc/claude/{}/v1'.format(ORG_ID)
openai.api_key = SESSION_KEY

response = openai.ChatCompletion.create(model="gpt-3.5-turbo", 
                                        messages=[{"role": "user", "content": "讲一个笑话"}], 
                                        stream=True)
result = ''
for chunk in response:
    try:
        result += chunk['choices'][0]['delta']['content']
    except:
        continue

print(result)
```

<img width="1221" alt="Snipaste_2023-08-02_00-50-18" src="https://github.com/UNICKCHENG/openai-proxy/assets/32270702/8a8be6b6-fc7f-4813-b0a6-d9799c177f44">

![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/0b52382d-73bd-453f-8587-63cd465bd3c5)

**Comment by darrelwangsz** [comment]
用推荐的 SeleOS 自己搞的

**Comment by darrelwangsz** [comment]
我试试

**Comment by darrelwangsz** [comment]
Traceback (most recent call last):
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 5, in <module>
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
  File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)

有这个错误~~

**Comment by darrelwangsz** [comment]
> > Traceback (most recent call last):
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 403, in handle_error_response
> > error_data = resp["error"]
> > TypeError: string indices must be integers
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
> > coro = func()
> > File "", line 5, in
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
> > return super().create(*args, **kwargs)
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
> > response, _, api_key = requestor.request(
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
> > resp, got_stream = self._interpret_response(result, stream)
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
> > self._interpret_response_line(
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
> > raise self.handle_error_response(
> > File "/Users/darrel/project/pandora-chatgpt/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 405, in handle_error_response
> > raise error.APIError(
> > openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)
> 
> 看样子是网络请求错误，出现 Internal Server Error，试试加上代理。
> 
> 或者把 `https://openai.aihey.cc` 改成你自建的地址

看了下，并不是，而是Cookie没处理好，去掉前面的前缀就可以，这个报错误可读性有点差，现在可以了，我多观察下。 
谢谢您的热情！！！
