### ISSUE TITLE
错误反馈: vercel部署代理后，在next web上设置好参数后输入问题显示Unexpected end of JSON input

### ISSUE THREAD

**Issue by ychappyboy** [UNICKCHENG/openai-proxy#72]
### 能告诉我发生了什么么？What happened?

之前在vercel部署代理后在next web可以正常时候，最近无法收到回复了,提示Unexpected end of JSON input

**Comment by UNICKCHENG** [comment]
方便提供详细点的截图信息么

**Comment by ychappyboy** [comment]
> 方便提供详细点的截图信息么
大神请看截图
![1](https://github.com/UNICKCHENG/openai-proxy/assets/132530676/df97760a-c281-471d-9053-27f3a5b6bae1)
![2](https://github.com/UNICKCHENG/openai-proxy/assets/132530676/96cde3c4-7ea7-4aa0-8aaf-c82bcbd7260d)
![图片3](https://github.com/UNICKCHENG/openai-proxy/assets/132530676/b0d9a7c4-ab2d-4d5e-821d-8c24b4ce579d)
另外，我使用你提供的代理https://openai.aihey.cc/配合{organization_uuid}和session可以正常输出，只不过响应比较慢

**Comment by RyanNiu** [comment]
+1

**Comment by UNICKCHENG** [comment]
@ychappyboy @RyanNiu 这个问题还存在么，我这边没有复现哎

![openai-proxy](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/ebcf4d56-3f86-48ec-bd33-db62c13b3e91)

如果还是存在，方便提供 log 页面的报错信息么，另外 vercel 是付费版的吧，不然可能会请求超时（见 #10 

![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/3c59f6f0-3baa-4468-9e7e-b965a11d53ac)

**Comment by ychappyboy** [comment]
@UNICKCHENG 你好，这样可以吗
![图片1](https://github.com/UNICKCHENG/openai-proxy/assets/132530676/b9c9ae73-99bd-4740-8b0d-bfda90a7f378)
![图片2](https://github.com/UNICKCHENG/openai-proxy/assets/132530676/b3e511b6-c632-4abd-adf3-4c0c218e6c44)

**Comment by ychappyboy** [comment]
@UNICKCHENG Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: /var/task/node_modules/cycletls/dist/index: No such file or directory

Error Processing Request (please open an issue https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) -> /bin/sh: /var/task/node_modules/cycletls/dist/index: No such file or directory

Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: kill ESRCH","reason":{"errorType":"Error","errorMessage":"kill ESRCH","code":"ESRCH","errno":-3,"syscall":"kill","stack":["Error: kill ESRCH","    at process.kill (node:internal/process/per_thread:233:13)","    at /var/task/node_modules/cycletls/dist/index.js:59:25","    at new Promise (<anonymous>)","    at cleanExit (/var/task/node_modules/cycletls/dist/index.js:58:13)","    at Socket.<anonymous> (/var/task/node_modules/cycletls/dist/index.js:86:19)","    at Socket.emit (node:events:514:28)","    at addChunk (node:internal/streams/readable:324:12)","    at readableAddChunk (node:internal/streams/readable:297:9)","    at Readable.push (node:internal/streams/readable:234:10)","    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: kill ESRCH","    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)","    at process.emit (node:events:526:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown

**Comment by UNICKCHENG** [comment]
似乎是 <https://github.com/Danny-Dasilva/CycleTLS> 这个组件引起的，你试试以下几个方案

## 方式 1：vercel 项目设置中替换默认的运行脚本

```
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 && next start
```
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/ecd2bf38-13b0-49a0-a7dc-bb71b99761fc)

## 方式 2：使用 docker 来部署，如借助 Sealos 平台来部署 docker
具体方式可参考 https://mp.weixin.qq.com/s/qbyKE_Uf_3xbWWqFKidreA

## 方式 3：改用第三方 api 来使用 claude api，如 [dify.ai](https://docs.dify.ai/application/developing-with-apis) (#81) 
![image](https://github.com/UNICKCHENG/openai-proxy/assets/32270702/57d077e7-ef07-4b46-a98a-c37170e3e623)

**Comment by ychappyboy** [comment]
@UNICKCHENG 方案一试了还是出现相同错误，方案二可以正常使用，但是无法实现打印机流的效果，谢谢！打印机效果可以在 Sealos 平台实现吗？

**Comment by UNICKCHENG** [comment]
之前 #73 也提到过，目前打印机效果暂时不知道咋实现。因为 [CycleTLS]( https://github.com/Danny-Dasilva/) 模拟 TLS 请求后拿到的是全部回复结果，如果再刻意按流输出（打印机流），就会牺牲响应速度。回头我再看看还有其他解决方案

> @UNICKCHENG 方案一试了还是出现相同错误，方案二可以正常使用，但是无法实现打印机流的效果，谢谢！打印机效果可以在 Sealos 平台实现吗？
